export const FETCH_RECORDS_SUCCESS = "FETCH_RECORDS_SUCCESS";
export const FETCH_RECORDS_REQUEST = "FETCH_RECORDS_REQUEST";
export const FETCH_RECORDS_FAILURE = "FETCH_RECORDS_FAILURE";

export const CREATE_RECORD_SUCCESS = "CREATE_RECORD_SUCCESS";
export const CREATE_RECORD_REQUEST = "CREATE_RECORD_REQUEST";
export const CREATE_RECORD_FAILURE = "CREATE_RECORD_FAILURE";

export const DELETE_RECORD_SUCCESS = "DELETE_RECORD_SUCCESS";
export const DELETE_RECORD_REQUEST = "DELETE_RECORD_REQUEST";
export const DELETE_RECORD_FAILURE = "DELETE_RECORD_FAILURE";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";

export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";
export const SIGNIN_REQUEST = "SIGNIN_REQUEST";

export const CONFIRM_CODE_SUCCESS = "CONFIRM_CODE_SUCCESS";
export const CONFIRM_CODE_FAILURE = "CONFIRM_CODE_FAILURE";
export const CONFIRM_CODE_REQUEST = "CONFIRM_CODE_REQUEST";

export const GET_ERRORS = "GET_ERRORS";

export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";